spring:
   profiles:
      active:
      - dev
---
server:
   port: 9004
   
spring:
   profiles: dev
   application:
      name:  clould-config-user-client
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.225:3306/wenlv_2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      dbcp2:
         min-idle: 5
         initial-size: 5
         max-total: 15
         max-wait-millis: 200
         
mybatis-plus:
   typeAliasesPackage: com.wenlv.Entity
   mapper-locations: classpath:mybatis/mapper/**/*.xml
   cache-enabled: true
   global-config:
      db-config:
         id-type: AUTO
         logic-delete-value: -1
         logic-not-delete-value: 0
      banner: false
   configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      call-setters-on-nulls: true
      jdbc-type-for-null: 'null'
      
eureka:
   client:
      service-url:
         defaultZone:  http://wenlv-eureka7001.com:7001/eureka/
   instance:
      instance-id: wenlv-user-9004.com
      prefer-ip-address: true

info:
   app.name: springcloud-cloudConfig01
   company.name: www.sopark.net
   build.artifactId: $project.artifactId$
   build.version: $project.version$
   
---
server:
   port: 9004
   
spring:
   profiles: test
   application:
      name:  clould-config-user-client
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.225:3306/wenlv?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      dbcp2:
         min-idle: 5
         initial-size: 5
         max-total: 15
         max-wait-millis: 200
        
mybatis-plus:
   typeAliasesPackage: com.wenlv.Entity
   mapper-locations: classpath:mybatis/mapper/**/*.xml
   cache-enabled: true
   global-config:
      db-config:
         id-type: AUTO
         logic-delete-value: -1
         logic-not-delete-value: 0
      banner: false
   configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      call-setters-on-nulls: true
      jdbc-type-for-null: 'null'

eureka:
   client:
      service-url:
         defaultZone:  http://wenlv-eureka7001.com:7001/eureka/
   instance:
      instance-id: wenlv-user-9004.com
      prefer-ip-address: true

info:
   app.name: springcloud-cloudConfig01
   company.name: www.sopark.net
   build.artifactId: $project.artifactId$
   build.version: $project.version$