spring:
   profiles:
      active:
      - dev
---
server:
   port: 9004
   
spring:
   profiles: dev
   application:
      name:  clould-config-user-client
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
#      driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
      driver-class-name: com.mysql.cj.jdbc.Driver  #mysql驱动包
      url: jdbc:mysql://192.168.0.225:3306/wenlv_2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true #数据库名称
      username: root
      password: 123456
      dbcp2:
         min-idle: 5 #数据库连接池最小维持连接数
         initial-size: 5 #初始化连接数
         max-total: 15 #最大连接数
         max-wait-millis: 200 #等待连接获取得最大超时时间
#redis配置文件
   redis:
#      open: false  # 是否开启redis缓存  true开启   false关闭
      database: 0
      host: 192.168.0.222
      port: 6379
      password:    # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      jedis:
         pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
#debug: true
         
mybatis-plus:
   typeAliasesPackage: com.wenlv.Entity #所有entity别名类所在包
   mapper-locations: classpath:mybatis/mapper/**/*.xml #mapper的映射文件
#   config-location:   classpath:mybatis/mybatis.cfg.xml      #mybatis配置文件所在路径
#实体扫描，多个package用逗号或者分号分隔
   cache-enabled: true #开启二级缓存
   global-config:
      db-config:
         id-type: AUTO
#数据库相关配置
         logic-delete-value: -1
#主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
         logic-not-delete-value: 0
      banner: false
   configuration:
      map-underscore-to-camel-case: true
#原生配置
      cache-enabled: true
      call-setters-on-nulls: true
      jdbc-type-for-null: 'null'
      
#将服务注册到eureka server中
eureka:
   client:
      service-url:
         defaultZone:  http://wenlv-eureka7001.com:7001/eureka/,http://wenlv-eureka7002.com:7002/eureka/,http://wenlv-eureka7003.com:7003/eureka/
   instance:                                    #入驻eureka实例取一个别名
      instance-id: wenlv-user-9004.com         #自定义服务器名称提示(带hystrix)
      prefer-ip-address: true                              #访问路径可以显示IP地址

#添加本服务的说明和配置信息      
info:
   app.name: springcloud-cloudConfig01
   company.name: www.sopark.net
   build.artifactId: $project.artifactId$
   build.version: $project.version$