spring:
   profiles:
      active:
      - dev
---
server:
   port: 7003               #注册中心占用9004端口号，冒号后面必须跟空格
   
spring:
   profiles: dev      #开发环境
   application:
      name:  clould-config-eureka-client
      
eureka:
   instance:
      hostname: wenlv-eureka7001.com
   client:
      register-with-eureka: false            #当前的eureka-server自己不注册金服务列表中
      fetch-registry: false                  #不通过eureka获取注册信息
      service-url:
         defaultZone: http://wenlv-eureka7001.com:7001/eureka/
---
server:
   port: 7003               #注册中心占用9004端口号，冒号后面必须跟空格
   
spring:
   profiles: test      #测试环境
   application:
      name:  clould-config-eureka-client
      
eureka:
   instance:
      hostname: wenlv-eureka7001.com
   client:
      register-with-eureka: false            #当前的eureka-server自己不注册金服务列表中
      fetch-registry: false                  #不通过eureka获取注册信息
      service-url:
         defaultZone: http://wenlv-eureka7001.com:7001/eureka/