spring:
   profiles:
      active:
      - dev

---
server:
   port: 7001
   
spring:
   profiles: dev
   application:
      name:  clould-config-eureka-client
      
eureka:
   instance:
      hostname: wenlv-eureka7001.com
   client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
         defaultZone: http://wenlv-eureka7001.com:7001/eureka/
---
server:
   port: 7001
   
spring:
   profiles: test
   application:
      name:  clould-config-eureka-client
      
eureka:
   instance:
      hostname: wenlv-eureka7001.com
   client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
         defaultZone: http://wenlv-eureka7001.com:7001/eureka/